[DBDev]
User = "root"
Pass = "root"
Addr = "localhost:3306"
DBName = "oims"
[DB]
User = "oims"
Pass = "root"
Addr = "localhost:3306"
DBName = "oims"
[Server]
Port = ":12308"
Sign = "spppk"
[Path]
Result = "/result"
History = "/history"
Log = "/log"